### ISSUE TITLE
stroke width not properly being pre processed

### ISSUE THREAD

**Issue by Happyrobot33** [Chlumsky/msdfgen#213] opened 2024-11-14 16:07 UTC
Using this SVG file, the ellipses is not being pre processed to have its stroke width represented, and the inside contour is just missing.

![svg_icon phx ver 1 1 (1)](https://github.com/user-attachments/assets/d48ea2e5-0a41-470c-9d67-f84a1c490190)

![image](https://github.com/user-attachments/assets/a4f2aefa-fa4f-4d98-a5a2-2d5967e2a2ce)

**Comment by Happyrobot33** [comment] 2024-11-14 16:23
seems like its just because it doesnt read in style for each svg shape entry individually, so it doesnt know to adjust how its adding things to skia

**Comment by Chlumsky** [comment] 2024-11-14 16:29
SVG import is for actual geometry only. Effects like strokes, gradients, shadows are not and will not be supported. This is not a bug. You need to convert your strokes to paths.

**Comment by Happyrobot33** [comment] 2024-11-14 18:12
> SVG import is for actual geometry only. Effects like strokes, gradients, shadows are not and will not be supported. This is not a bug. You need to convert your strokes to paths.

I understand the reasoning for gradients and shadows as those are color based affects, but for strokes like this, the visual geometry is different than what is generated. Wouldnt it be worth allowing the pre processor to expand out the strokes into a path automatically? even if I was to use a circle that was filled, if it had a stroke width the result would be different than what should be generated for it as it wouldnt take into account the real outer contour

**Comment by Chlumsky** [comment] 2024-11-15 17:04
SVG is only supported as a more convenient way to pass the vector path, there is no intention to try to perfectly match how it would be typically rendered. Also, from a practical standpoint, for anything other than a circle or rectangle, converting a stroke to path is actually a very complex operation beyond the scope of this library, but that is not the reason why it won't be supported. Sorry.

**Closed by Chlumsky** 2024-11-15 17:04 UTC
