### ISSUE TITLE
Parameters to reproduce first figure

### ISSUE THREAD

**Issue by rougier** [Chlumsky/msdfgen#1] opened 2016-04-26 13:58 UTC
Thank you very much for publishing your code ! I'm eager to read your paper.

I've tried to play a bit with the program and I'm trying to to reproduce your fir figure (capital 'A' / Arial font) but the output is not so good. I've been using:

```
./msdfgen msdf -font Arial.ttf '0x41' -o msdf.png -size 16 16 -pxrange 2 -autoframe -testrender render.png 256 256
```

and I get:

![render](https://cloud.githubusercontent.com/assets/327203/14820597/a28bad82-0bc7-11e6-82f8-98bb9defc67b.png)

Any idea what is wrong in my command line ?

**Comment by Chlumsky** [comment] 2016-04-26 15:22
Unfortunatelly, my method only improves corners and just like monochrome distance fields, doesn't handle well thin strokes that only span 1 or 2 pixels in the distance field. In the example, I used Arial Bold, which has thicker strokes. You should be able to reproduce it using the arguments in example.bat. But I admit the example is a bit biased, since 16x16 is almost never a sufficient size for a glyph's distance field, and I would strongly recommend choosing a larger size.

**Comment by rougier** [comment] 2016-04-26 15:47
Thanks for the explanation, I wanted to be sure to have understood usage of your code.

There might room for improvement on the technique, maybe on the shader side ? If you look at this thread (you will realize we were waiting for your code) you'll see some possible tips: https://github.com/rougier/freetype-gl/issues/110 and https://github.com/rougier/freetype-gl/issues/97.

**Comment by Chlumsky** [comment] 2016-04-26 16:46
I'm afraid this cannot be fixed by any fragment shader (not to mention the test renders aren't generated with an actual shader, so it can't be a problem with fwidth or something like that), it's just the nature of distance fields. However, you can take advantage of the multiple channels to represent a thin stroke as the intersection of larger areas. You can do this by just using a different edge coloring strategy:

![render](https://cloud.githubusercontent.com/assets/18639794/14826600/e902ac0e-0bde-11e6-9a95-d14b9834441f.png)
[a_thin.txt](https://github.com/Chlumsky/msdfgen/files/237063/a_thin.txt) (pass this as -shapedesc)

Although you would need more color channels to simultaneously also take care of corners, and I suspect certain configurations of multiple thin strokes would also cause problems.

**Comment by rougier** [comment] 2016-04-26 17:46
I definitely need to read you paper to get a better understanding of your technique.

By the way, I've been playing a bit more with the Arial font using different settings but in most cases, the upper pat of the internal left oblique line of the A letter seems to be curved (compared to the right) one. Could this be some kind of bug or a side-effect ?

```
msdfgen msdf -font Arial.ttf '0x41' -o msdf.png -size 32 32 -pxrange 4 -testrender render.png 1024 1024
```
![render](https://cloud.githubusercontent.com/assets/327203/14828420/389349ec-0be7-11e6-9d5a-861f82e9fccf.png)

**Comment by Chlumsky** [comment] 2016-04-26 19:15
Actually, I'm pretty sure that's exactly how it's defined in the Arial typeface. I have just tested that Firefox renders it the same way.

**Comment by rougier** [comment] 2016-04-26 19:53
Oh yes, you're right. Never paid attention to this detail.

**Comment by behdad** [comment] 2016-04-26 20:49
> Oh yes, you're right. Never paid attention to this detail.

That's called in ink trap!

**Comment by rougier** [comment] 2016-04-27 05:20
Excellent: https://en.wikipedia.org/wiki/Ink_trap

**Closed** 2016-04-28 12:34 UTC
