### ISSUE TITLE
Using vcpkg leads to compiler error in VS2022

### ISSUE THREAD

**Issue by Murk42** [Chlumsky/msdfgen#186] opened 2023-09-02 20:07 UTC
When using vcpkg to manage the msdfgen library, including it yields compiler errors.
`MSDFGEN_PUBLIC` is not defined inside the "generator-config.h" file. And the static variables `msdfgen::ErrorCorrectionConfig::defaultMinDeviationRatio` and `msdfgen::ErrorCorrectionConfig::defaultMinImproveRatio` aren't implemented.
Here are the errors but i don't think they are anything meaningfull:
![Capture](https://github.com/Chlumsky/msdfgen/assets/70409510/427812e5-536c-4fb6-9d8c-be02df29dff9)

**Comment by Chlumsky** [comment] 2023-09-02 20:48
I am assuming that you use vcpkg directly in Visual Studio and don't use CMake to generate your project and link MSDFgen. I don't use it this way so I don't know what the correct solution here is, but the problem is that the MSDFgen library exports some global defines for projects that depend on it (this is normally handled by CMake). Those are:

- `MSDFGEN_USE_CPP11`
- `MSDFGEN_PUBLIC=__declspec(dllimport)` for DLL linkage, `MSDFGEN_PUBLIC=` for static
- `MSDFGEN_USE_LIBPNG` when using `extensions` default feature
- `MSDFGEN_USE_SKIA` when using `geometry-preprocessing` default feature

**Comment by Murk42** [comment] 2023-09-04 13:43
@Chlumsky Yeah you got everything right, thank you for the reply! :)

**Comment by amadeusCaleb** [comment] 2023-09-28 12:24
@Chlumsky I also had the same issue and was able to resolve it following the directions above. 

P.S. thank you for making this library!

**Comment by Chlumsky** [comment] 2023-11-14 22:55
This issue should be fixed in version 1.11.

**Closed by Chlumsky** 2023-11-14 22:55 UTC
